name: mask_rcnn_cpu
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python=3.5
    - matplotlib
    - numpy
    - opencv3
    - pillow
    - scipy
    - tensorflow=1.3.*
    - scikit-learn
    - scikit-image
    - h5py
    - eventlet
    - seaborn
    - pandas
    - ffmpeg
    - imageio
    - keras
    - cython
    - pip:
        - moviepy